version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: routine_db_container
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: routine_db
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
