openapi: 3.0.3
info:
  title: Routine & Alerts API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /routine/{id}:
    get:
      summary: Recupera tutte le routine di un utente
      tags: [Routine]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID utente
      responses:
        "200":
          description: Lista di routine
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Routine"

    delete:
      summary: Elimina una routine
      tags: [Routine]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Eliminazione avvenuta con successo

    patch:
      summary: Modifica una routine
      tags: [Routine]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Routine"
      responses:
        "200":
          description: Routine aggiornata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Routine"
    put:
      summary: Sostituisci una routine
      tags: [Routine]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Routine"
      responses:
        "200":
          description: Routine sostituita
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Routine"

  /routine:
    post:
      summary: Crea una nuova routine
      tags: [Routine]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Routine"
            example:
              nomeRoutine: "vskovdk"
              alerts:
                - oraInizio: "14:00"
                  oraFine: "18:00"
                  codici:
                    - descrizione: 1
      responses:
        "201":
          description: Routine creata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Routine"

  /alerts/{id}:
    get:
      summary: Recupera gli alert di una routine
      tags: [Alerts]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID della routine
      responses:
        "200":
          description: Lista di alert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Alert"

    delete:
      summary: Elimina un alert
      tags: [Alerts]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Eliminazione avvenuta con successo

    patch:
      summary: Modifica un alert
      tags: [Alerts]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Alert"
      responses:
        "200":
          description: Alert aggiornato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alert"

    put:
      summary: Sostituisce un alert
      tags: [Alerts]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Alert"
      responses:
        "200":
          description: Alert sostituito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alert"

  /alerts:
    post:
      summary: Crea un alert
      tags: [Alerts]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Alert"
            example:
              oraInizio: "14:00"
              oraFine: "18:00"
              codici:
                - descrizione: 1
      responses:
        "201":
          description: Alert creato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alert"

components:
  schemas:
    Routine:
      type: object
      properties:
        nomeRoutine:
          type: string
        alerts:
          type: array
          items:
            $ref: "#/components/schemas/Alert"

    Alert:
      type: object
      properties:
        oraInizio:
          type: string
          example: "14:00"
        oraFine:
          type: string
          example: "18:00"
        citta:
          type: string
          example: "Silvi"
        tipoMessaggio:
          type: string
          example: "Sveglia alle 6"
        codici:
          type: array
          items:
            type: object
            properties:
              descrizione:
                type: string
