spring.application.name=routine-api-service
spring.profiles.active=prod
logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=none
weather.codes.remote=https://www.weatherapi.com/docs/weather_conditions.json
