spring.application.name=routine-api-service
spring.profiles.active=prod
logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always

server.port=8080

# Configurazione User API Client
user-api.url=http://localhost:8084

# Logging Feign
logging.level.tech.aesys.finale.routine.client=DEBUG