CREATE TABLE IF NOT EXISTS routine
(
    routine_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_routine VARCHAR(255) NOT NULL,
    CONSTRAINT pk_routine PRIMARY KEY (routine_id)
);

CREATE TABLE IF NOT EXISTS alert
(
    alert_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ora_inizio     TIMESTAMP                               NOT NULL,
    ora_fine       TIMESTAMP                               NOT NULL,
    testo_notifica VARCHAR(100)                            NOT NULL,
    citta          VARCHAR(100)                            NOT NULL,
    routine_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_alert PRIMARY KEY (alert_id)
);

CREATE TABLE IF NOT EXISTS alert_codici
(
    alert_id BIGINT       NOT NULL,
    codice   VARCHAR(255) NOT NULL
);

ALTER TABLE alert
    ADD CONSTRAINT FK_ALERT_ON_ROUTINE FOREIGN KEY (routine_id) REFERENCES routine (routine_id);

ALTER TABLE alert_codici
    ADD CONSTRAINT fk_alert_codici_on_alert FOREIGN KEY (alert_id) REFERENCES alert (alert_id);

CREATE TABLE IF NOT EXISTS condizioni_meteo
(
    codice BIGINT       NOT NULL,
    tipo   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_condizioni_meteo PRIMARY KEY (codice)
);


INSERT INTO routine (routine_id, nome_routine) VALUES (1, 'Bongiorn eh');
INSERT INTO alert (alert_id, ora_inizio, ora_fine, testo_notifica, citta, routine_id) VALUES (1, '2024-07-01 07:00:00', '2024-07-01 08:00:00', 'Bongiorn eh.', 'Silvi', 1);
INSERT INTO alert_codici (alert_id, codice) VALUES (1, 'NUVOLOSO');
-- INSERT INTO condizioni_meteo (codice, tipo) VALUES (1, 'NUVOLOSO');